name: Run Tests

on:
  push:
    branches:
      - main  # Or your main branch name
  pull_request:
    branches:
      - main  # Or your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  
        
    - name: Install Docker
      uses: docker/setup-docker-action@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest mock  

    - name: Run tests
      run: |
        pytest tests.py
